name: flutter_core_datz
description: "A new Flutter package project."
version: 1.0.4+11
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  # Dio for Api Calling
  dio: any
  logger: any
  # routing
  auto_route: any

  # Language
  easy_localization: any
  # support dart core
  intl: any
  collection: any #array, List method
  dartz: any
  # native
  device_info_plus: any #get device infocollection: any #array, List method
  path_provider: any
  connectivity_plus: any
  # LocalDB
  # sqflite: any
  shared_preferences: any
  get_it: any
  # Widget
  toastification: any #show toast error
  flutter_svg: any
  cached_network_image: any
  #
  # flutter_form_builder: any #bingding form
  form_builder_validators: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  auto_route_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages